export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const CREATE_CART_ENTRY = 'CREATE_CART_ENTRY';
export const UPDATE_CART_ENTRY = 'UPDATE_CART_ENTRY';
export const REMOVE_CART_ENTRY = 'REMOVE_CART_ENTRY';
export const SET_PRODUCT_QTY = 'SET_PRODUCT_QTY';